version: '3'

services:

  pandoc:
    build: ./scatterdoc
    container_name: scatterdoc
    environment:
     - loglevel=none
    volumes:
     - "./scatterdoc/workspace:/home/scatterdoc/workspace"
    working_dir: "/home/scatterdoc/workspace"
